FROM amd64/ros:noetic-perception-focal


ARG DEBIAN_FRONTEND=noninteractive
ARG ROS_DISTRO=noetic

WORKDIR /root

# install ORBSLAM3 ROS package

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get update && \
    apt-get install -y ros-noetic-image-geometry ros-noetic-pcl-ros ros-noetic-xacro \
    ros-noetic-navigation \
    ros-noetic-robot-localization \
    ros-noetic-robot-state-publisher \
    ros-noetic-cv-bridge unzip pkg-config autoconf \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    # Use libvtk5-dev, libgtk2.0-dev in ubuntu 16.04 \
    libvtk7-dev libgtk-3-dev \
    libcanberra-gtk-module libcanberra-gtk3-module \
    libatlas-base-dev gfortran \
    libparmetis-dev \
    python3-wstool \
    # libtbb recommended for speed: \
    libtbb-dev \
    software-properties-common \
    git \
    build-essential \
    cmake \
    libeigen3-dev \
    ros-${ROS_DISTRO}-hector-trajectory-server \
    ros-${ROS_DISTRO}-rviz \
    python3-catkin-tools \
    python3-pip \
    libopencv-contrib-dev \
    libopencv-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean


RUN python3 -m pip install evo

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc
RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc


RUN apt-get update \
    && apt install -y software-properties-common \
    && add-apt-repository -y ppa:borglab/gtsam-release-4.0 \
    && apt-get update \
    && apt install -y libgtsam-dev libgtsam-unstable-dev \
    && rm -rf /var/lib/apt/lists/*

